services:
  api-gateway:
    build: .
    image: ghcr.io/voltcast-a-ase-project/api-gateway-python/api-gateway:latest
    networks:
      - VoltCast_Network
    ports:
      - "22200:22200"
    expose:
      - "22200"
    environment:
      DB_NAME: ""
      ACCESS_TOKEN_EXPIRE_MINUTES: 0
      JWT_SECRET: ""
      ALGORITHM: ""

networks:
  VoltCast_Network:
    external: true
