services:
  api-gateway:
    build: .
    image: ghcr.io/voltcast-a-ase-project/api-gateway-python/api-gateway:latest
    networks:
      - VoltCast_Network
    ports:
      - "22200:22200"
    expose:
      - "22200"
    environment:
      - DB_NAME=${DB_NAME}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - JWT_SECRET=${JWT_SECRET}
      - ALGORITHM=${ALGORITHM}

networks:
  VoltCast_Network:
    external: true
