name: Docker image and acceptance and performance tests
on:
  push:
    branches:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}
  COMPOSE_FILE: docker-compose.yml

jobs:
  # Job builds docker image and pushes it to GHCR
  build-and-push:
    name: Build and push docker image to Github registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}/web
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker images
        run: |
          # Build and push each service defined in docker-compose.yml
          docker compose -f ${{ env.COMPOSE_FILE }} build
          docker compose -f ${{ env.COMPOSE_FILE }} push

  # Job runs acceptance tests
  acceptance-test:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - name: Setup container
        run: |
          docker network create VoltCast_Network
          
          docker run -d --name api-gateway -p 22200:22200 \
            -e "DB_NAME=$DB_NAME" \
            -e "ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES" \
            -e "JWT_SECRET=$JWT_SECRET" \
            -e "ALGORITHM=$ALGORITHM" \
            ghcr.io/voltcast-a-ase-project/api-gateway-python/api-gateway:latest

          docker run -d --name fronius-ms -p 8081:8081 \
            -e MOCKING_ENABLED=true \
            ghcr.io/voltcast-a-ase-project/fronius-microservice/fronius-ms:latest

          docker run -d --name kostal-ms -p 8082:8082 \
            ghcr.io/voltcast-a-ase-project/kostal-microservice/kostal-ms:latest

          docker run -d --name shelly-ms -p 8083:8083 \
            ghcr.io/voltcast-a-ase-project/shelly-microservice/shelly-ms:latest

          docker run -d --name alerting-ms -p 8087:8087 \
            ghcr.io/voltcast-a-ase-project/alerting_service/alert-ms:latest

          docker network connect VoltCast_Network api-gateway

          docker network connect VoltCast_Network fronius-ms
          
          docker network connect VoltCast_Network kostal-ms
          
          docker network connect VoltCast_Network shelly-ms
          
          docker network connect VoltCast_Network alerting-ms
          

      - name: Install Python, Java Runtime and Taurus
        run: |
          sudo apt-get update
          sudo apt-get install python3 default-jre-headless python3-tk python3-dev libxml2-dev libxslt-dev zlib1g-dev net-tools
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install bzt

      - name: Run Acceptance Tests
        run: |
          source .venv/bin/activate
          bzt acceptance_tests.jmx

      - name: Print docker logs
        run: |
          docker logs api-gateway
